apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nile-fe
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    # nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    # nginx.ingress.kubernetes.io/preserve-trailing-slash: "true"
    # nginx.ingress.kubernetes.io/secure-backends: "true"
    # nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    # nginx.ingress.kubernetes.io/whitelist-source-range: "211.177.23.91, 58.120.29.19"
spec:
  tls:
    - hosts:
        - www.nile.io
      secretName: nile-io
  rules:
    - host: www.nile.io
      http:
        paths:
          - pathType: ImplementationSpecific
            path: /?(.*)
            backend:
              service:
                name: nile-fe
                port:
                  number: 80
